[package]
name = "zero2prod"
version = "0.1.0"
edition = "2021"

[target.x86_64-pc-windows-msvc]
linker = "rust-lld.exe"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
