version: '3.9'

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - "5435:5432"
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=newsletter
  zero2prod:
    image: zero2prod:latest
    depends_on:
      - postgres
    ports:
      - "8000:8000"