database:
  host: "localhost"
  port: 5435
  username: "postgres"
  password: "password"
  database_name: "newsletter"
application:
  port: 8000
  host: 127.0.0.1
email_client:
  base_url: "localhost"
  sender_email: "test@koenmolenaar.nl"
  timeout_milliseconds: 10000
